### ISSUE TITLE
Issue with nav bar in mobile screen

### ISSUE THREAD

**Issue by VasaviLagishetty** [devskrate/biowith#4]
Nav option bar is not closing once it is clicked 
![nav_bar_issue](https://user-images.githubusercontent.com/47534164/84687976-2a509e80-af5c-11ea-81fa-2ed97da22432.png)

**Comment by SriSatyaLokesh** [comment]
@puneethkanna  keep this as high priority task

**Comment by puneethkanna** [comment]
Will look into the issue, will fix it by tomorrow evening.
